# Dotnet Core 5 Pipelines

image: mcr.microsoft.com/dotnet/sdk:5.0-bullseye-slim

pipelines:
  branches: 
    dev:
      - step: 
          name: Build and Test
          caches:
            - dotnetcore
          script:
            - REPORTS_PATH=./test-reports/build_${BITBUCKET_BUILD_NUMBER}
            - dotnet restore
            - dotnet build --no-restore --configuration Release
            - dotnet test --no-build --configuration Release --test-adapter-path:. --logger:"junit;LogFilePath=$REPORTS_PATH/junit.xml"
      - step: 
          name: Publish
          caches:
            - dotnetcore
          script:
            - dotnet restore
            - dotnet publish --configuration Release --no-build -o ./publish
          artifacts:
            - ./publish/**

  pull-requests:
    '**':
      - step:
          name: Build and Test
          caches:
            - dotnetcore
          script:
            - REPORTS_PATH=./test-reports/build_${BITBUCKET_BUILD_NUMBER}
            - dotnet restore
            - dotnet build --no-restore --configuration Release
            - dotnet test --no-build --configuration Release --test-adapter-path:. --logger:"junit;LogFilePath=$REPORTS_PATH/junit.xml"
      - step:
          name: Publish
          caches:
            - dotnetcore
          script:
            - dotnet restore
            - dotnet build --no-restore --configuration Release
            - dotnet publish --configuration Release --no-build -o ./publish
          artifacts:
            - ./publish/**