# Dotnet Core 5 Pipelines

image: mcr.microsoft.com/dotnet/sdk:5.0-bullseye-slim

pipelines:
  branches: 
    dev:
      - step:
          name: Lint
          caches:
            - dotnetcore
          script:
            - export SOLUTION_NAME=diabetes-backend
            - export REPORTS_PATH=linter-reports
            - dotnet new tool-manifest
            - dotnet tool install JetBrains.ReSharper.GlobalTools
            - dotnet tool restore
            - dotnet jb inspectcode ${SOLUTION_NAME}.sln --output="${REPORTS_PATH}/jb-${BITBUCKET_BUILD_NUMBER}.xml"
          artifacts:
            - linter-reports/**
      - step: 
          name: Build and Test
          caches:
            - dotnetcore
          script:
            - REPORTS_PATH=./test-reports/build_${BITBUCKET_BUILD_NUMBER}
            - dotnet restore
            - dotnet build --no-restore --configuration Release
            - dotnet test --no-build --configuration Release --test-adapter-path:. --logger:"junit;LogFilePath=$REPORTS_PATH/junit.xml"
      - step: 
          name: Publish
          caches:
            - dotnetcore
          script:
            - dotnet publish --configuration Release --no-build -o ./publish
          artifacts:
            - ./publish/**

  pull-requests:
    '**':
      - step:
          name: Lint
          caches:
            - dotnetcore
          script:
            - export SOLUTION_NAME=diabetes-backend
            - export REPORTS_PATH=linter-reports
            - dotnet new tool-manifest
            - dotnet tool install JetBrains.ReSharper.GlobalTools
            - dotnet tool restore
            - dotnet jb inspectcode ${SOLUTION_NAME}.sln --output="${REPORTS_PATH}/jb-${BITBUCKET_BUILD_NUMBER}.xml"
          artifacts:
            - linter-reports/**
      - step:
          name: Build and Test
          caches:
            - dotnetcore
          script:
            - REPORTS_PATH=./test-reports/build_${BITBUCKET_BUILD_NUMBER}
            - dotnet restore
            - dotnet build --no-restore --configuration Release
            - dotnet test --no-build --configuration Release --test-adapter-path:. --logger:"junit;LogFilePath=$REPORTS_PATH/junit.xml"